### ISSUE TITLE
OneLine error when using unity 2018

### ISSUE THREAD

**Issue by TinManTex** [Joey35233/FoxKit#5]
Reproduction:
Use Unity 2018.
Expand an element on the Form variation inspector.

The cause seems to be due to OneLine using a somewhat hacky way of getting the inspector window positioning no longer working due to changes from prior unity versions.

An issue should probably be created on OneLines github.

**Comment by Joey35233** [comment]
I'll still take a look and try and fix it, and maybe make a suggestion on the OneLine repository.

**Comment by Joey35233** [comment]
The maker of OneLine fixed the issue.
